// <auto-generated />
namespace SuperAwesomeApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NotWTF_AddMiddleName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NotWTF_AddMiddleName));
        
        string IMigrationMetadata.Id
        {
            get { return "201604141633143_NotWTF_AddMiddleName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
